var searchData=
[
  ['factory_20functions_0',['factory functions',['../group__array-factories.html',1,'Array factory functions'],['../group__scalar-factories.html',1,'Scalar factory functions']]],
  ['factory_20functions_20for_20creating_20data_20types_1',['Factory functions for creating data types',['../group__type-factories.html',1,'']]],
  ['factory_20functions_20for_20fields_20and_20schemas_2',['Factory functions for fields and schemas',['../group__schema-factories.html',1,'']]],
  ['factory_20functions_20for_20parquet_20arrow_20readers_3',['Factory functions for Parquet Arrow readers',['../group__parquet-arrow-reader-factories.html',1,'']]],
  ['family_4',['family',['../group__XXH3__family.html',1,'XXH3 family'],['../group__XXH32__family.html',1,'XXH32 family'],['../group__XXH64__family.html',1,'XXH64 family']]],
  ['fields_20and_20schemas_5',['Factory functions for fields and schemas',['../group__schema-factories.html',1,'']]],
  ['file_20formats_20for_20reading_20and_20writing_20datasets_6',['File formats for reading and writing datasets',['../group__dataset-file-formats.html',1,'']]],
  ['file_20system_20datasets_7',['File system datasets',['../group__dataset-filesystem.html',1,'']]],
  ['files_8',['High-level functions for writing CSV files',['../group__csv-write-functions.html',1,'']]],
  ['filesystem_20instances_9',['Functions for creating FileSystem instances',['../group__filesystem-factories.html',1,'']]],
  ['filesystem_20registration_10',['Helpers for FileSystem registration',['../group__filesystem-factory-registration.html',1,'']]],
  ['flight_20types_11',['Async Flight Types',['../group__flight-async.html',1,'']]],
  ['for_20allocating_20buffers_12',['Functions for allocating buffers',['../group__buffer-allocation-functions.html',1,'']]],
  ['for_20binary_20string_20arrays_13',['Concrete classes for binary/string arrays',['../group__binary-arrays.html',1,'']]],
  ['for_20binary_20string_20data_14',['Datatypes for binary/string data',['../group__binary-datatypes.html',1,'']]],
  ['for_20binary_20types_15',['Concrete builder subclasses for binary types',['../group__binary-builders.html',1,'']]],
  ['for_20calling_20functions_20useful_20for_20those_16',['Utilities for calling functions, useful for those',['../group__compute-internals.html',1,'']]],
  ['for_20compute_20functions_17',['Concrete option classes for compute functions',['../group__compute-concrete-options.html',1,'']]],
  ['for_20convenient_20expression_20creation_18',['Helpers for convenient expression creation',['../group__expression-convenience.html',1,'']]],
  ['for_20creating_20an_20incremental_20csv_20writer_19',['Functions for creating an incremental CSV writer',['../group__csv-writer-factories.html',1,'']]],
  ['for_20creating_20and_20executing_20execution_20plans_20',['Utilities for creating and executing execution plans',['../group__acero-api.html',1,'']]],
  ['for_20creating_20data_20types_21',['Factory functions for creating data types',['../group__type-factories.html',1,'']]],
  ['for_20creating_20filesystem_20instances_22',['Functions for creating FileSystem instances',['../group__filesystem-factories.html',1,'']]],
  ['for_20creating_20recordbatchwriter_23',['Functions for creating RecordBatchWriter',['../group__record-batch-writer-factories.html',1,'']]],
  ['for_20dictionary_20types_24',['Concrete builder subclasses for dictionary types',['../group__dictionary-builders.html',1,'']]],
  ['for_20fields_20and_20schemas_25',['Factory functions for fields and schemas',['../group__schema-factories.html',1,'']]],
  ['for_20filesystem_20registration_26',['Helpers for FileSystem registration',['../group__filesystem-factory-registration.html',1,'']]],
  ['for_20modification_20of_20expressions_27',['Functions for modification of Expressions',['../group__expression-passes.html',1,'']]],
  ['for_20nested_20arrays_28',['Concrete classes for nested arrays',['../group__nested-arrays.html',1,'']]],
  ['for_20nested_20data_29',['Datatypes for nested data',['../group__nested-datatypes.html',1,'']]],
  ['for_20nested_20types_30',['Concrete builder subclasses for nested types',['../group__nested-builders.html',1,'']]],
  ['for_20numeric_20arrays_31',['Concrete classes for numeric arrays',['../group__numeric-arrays.html',1,'']]],
  ['for_20numeric_20data_32',['Datatypes for numeric data',['../group__numeric-datatypes.html',1,'']]],
  ['for_20numeric_20types_33',['Concrete builder subclasses for numeric types',['../group__numeric-builders.html',1,'']]],
  ['for_20parquet_20arrow_20readers_34',['Factory functions for Parquet Arrow readers',['../group__parquet-arrow-reader-factories.html',1,'']]],
  ['for_20reading_20and_20writing_20datasets_35',['File formats for reading and writing datasets',['../group__dataset-file-formats.html',1,'']]],
  ['for_20run_20end_20encoded_36',['Concrete builder subclasses for run-end encoded',['../group__run-end-encoded-builders.html',1,'']]],
  ['for_20run_20end_20encoded_20arrays_37',['Concrete classes for run-end encoded arrays',['../group__run-end-encoded-arrays.html',1,'']]],
  ['for_20slicing_20buffers_38',['Functions for slicing buffers',['../group__buffer-slicing-functions.html',1,'']]],
  ['for_20temporal_20data_39',['Datatypes for temporal data',['../group__temporal-datatypes.html',1,'']]],
  ['for_20temporal_20types_40',['Concrete builder subclasses for temporal types',['../group__temporal-builders.html',1,'']]],
  ['for_20the_20various_20exec_20nodes_41',['Options classes for the various exec nodes',['../group__acero-nodes.html',1,'']]],
  ['for_20those_20extending_20acero_42',['Acero internals, useful for those extending Acero',['../group__acero-internals.html',1,'']]],
  ['for_20working_20with_20data_20in_20a_20row_20major_20format_43',['Utilities for working with data in a row-major format',['../group__execnode-row.html',1,'']]],
  ['for_20working_20with_20futures_44',['Functions for working with Futures',['../group__future-utilities.html',1,'']]],
  ['for_20working_20with_20the_20c_20data_20device_45',['Functions for working with the C data device',['../group__c-data-device-interface.html',1,'']]],
  ['for_20working_20with_20the_20c_20data_20interface_46',['for working with the c data interface',['../group__c-stream-interface.html',1,'Functions for working with the C data interface.'],['../group__c-data-interface.html',1,'Functions for working with the C data interface.']]],
  ['for_20writing_20csv_20files_47',['High-level functions for writing CSV files',['../group__csv-write-functions.html',1,'']]],
  ['format_48',['Utilities for working with data in a row-major format',['../group__execnode-row.html',1,'']]],
  ['formats_20for_20reading_20and_20writing_20datasets_49',['File formats for reading and writing datasets',['../group__dataset-file-formats.html',1,'']]],
  ['function_50',['ConcatenateTables function.',['../group__concat-tables.html',1,'']]],
  ['function_20api_51',['Abstract compute function API',['../group__compute-functions.html',1,'']]],
  ['function_20executors_52',['One-shot calls to obtain function executors',['../group__compute-function-executor.html',1,'']]],
  ['functions_53',['functions',['../group__array-factories.html',1,'Array factory functions'],['../group__compute-concrete-options.html',1,'Concrete option classes for compute functions'],['../group__compute-call-function.html',1,'One-shot calls to compute functions'],['../group__scalar-factories.html',1,'Scalar factory functions']]],
  ['functions_20for_20allocating_20buffers_54',['Functions for allocating buffers',['../group__buffer-allocation-functions.html',1,'']]],
  ['functions_20for_20creating_20an_20incremental_20csv_20writer_55',['Functions for creating an incremental CSV writer',['../group__csv-writer-factories.html',1,'']]],
  ['functions_20for_20creating_20data_20types_56',['Factory functions for creating data types',['../group__type-factories.html',1,'']]],
  ['functions_20for_20creating_20filesystem_20instances_57',['Functions for creating FileSystem instances',['../group__filesystem-factories.html',1,'']]],
  ['functions_20for_20creating_20recordbatchwriter_58',['Functions for creating RecordBatchWriter',['../group__record-batch-writer-factories.html',1,'']]],
  ['functions_20for_20fields_20and_20schemas_59',['Factory functions for fields and schemas',['../group__schema-factories.html',1,'']]],
  ['functions_20for_20modification_20of_20expressions_60',['Functions for modification of Expressions',['../group__expression-passes.html',1,'']]],
  ['functions_20for_20parquet_20arrow_20readers_61',['Factory functions for Parquet Arrow readers',['../group__parquet-arrow-reader-factories.html',1,'']]],
  ['functions_20for_20slicing_20buffers_62',['Functions for slicing buffers',['../group__buffer-slicing-functions.html',1,'']]],
  ['functions_20for_20working_20with_20futures_63',['Functions for working with Futures',['../group__future-utilities.html',1,'']]],
  ['functions_20for_20working_20with_20the_20c_20data_20device_64',['Functions for working with the C data device',['../group__c-data-device-interface.html',1,'']]],
  ['functions_20for_20working_20with_20the_20c_20data_20interface_65',['functions for working with the c data interface',['../group__c-stream-interface.html',1,'Functions for working with the C data interface.'],['../group__c-data-interface.html',1,'Functions for working with the C data interface.']]],
  ['functions_20for_20writing_20csv_20files_66',['High-level functions for writing CSV files',['../group__csv-write-functions.html',1,'']]],
  ['functions_20to_20convert_20a_20parquet_67',['Functions to convert a Parquet',['../group__parquet-to-arrow-schema-conversion.html',1,'']]],
  ['functions_20to_20convert_20an_20arrow_68',['Functions to convert an Arrow',['../group__arrow-to-parquet-schema-conversion.html',1,'']]],
  ['functions_20useful_20for_20those_69',['Utilities for calling functions, useful for those',['../group__compute-internals.html',1,'']]],
  ['futures_70',['Functions for working with Futures',['../group__future-utilities.html',1,'']]]
];
