var searchData=
[
  ['c_20data_20device_0',['Functions for working with the C data device',['../group__c-data-device-interface.html',1,'']]],
  ['c_20data_20interface_1',['c data interface',['../group__c-stream-interface.html',1,'Functions for working with the C data interface.'],['../group__c-data-interface.html',1,'Functions for working with the C data interface.']]],
  ['c_20type_20traits_2',['C-type-traits',['../group__c-type-traits.html',1,'']]],
  ['calling_20functions_20useful_20for_20those_3',['Utilities for calling functions, useful for those',['../group__compute-internals.html',1,'']]],
  ['calls_20to_20compute_20functions_4',['One-shot calls to compute functions',['../group__compute-call-function.html',1,'']]],
  ['calls_20to_20obtain_20function_20executors_5',['One-shot calls to obtain function executors',['../group__compute-function-executor.html',1,'']]],
  ['classes_20for_20binary_20string_20arrays_6',['Concrete classes for binary/string arrays',['../group__binary-arrays.html',1,'']]],
  ['classes_20for_20compute_20functions_7',['Concrete option classes for compute functions',['../group__compute-concrete-options.html',1,'']]],
  ['classes_20for_20nested_20arrays_8',['Concrete classes for nested arrays',['../group__nested-arrays.html',1,'']]],
  ['classes_20for_20numeric_20arrays_9',['Concrete classes for numeric arrays',['../group__numeric-arrays.html',1,'']]],
  ['classes_20for_20run_20end_20encoded_20arrays_10',['Concrete classes for run-end encoded arrays',['../group__run-end-encoded-arrays.html',1,'']]],
  ['classes_20for_20the_20various_20exec_20nodes_11',['Options classes for the various exec nodes',['../group__acero-nodes.html',1,'']]],
  ['compute_20function_20api_12',['Abstract compute function API',['../group__compute-functions.html',1,'']]],
  ['compute_20functions_13',['compute functions',['../group__compute-concrete-options.html',1,'Concrete option classes for compute functions'],['../group__compute-call-function.html',1,'One-shot calls to compute functions']]],
  ['concatenatetables_20function_14',['ConcatenateTables function.',['../group__concat-tables.html',1,'']]],
  ['concrete_20builder_20subclasses_20for_20binary_20types_15',['Concrete builder subclasses for binary types',['../group__binary-builders.html',1,'']]],
  ['concrete_20builder_20subclasses_20for_20dictionary_20types_16',['Concrete builder subclasses for dictionary types',['../group__dictionary-builders.html',1,'']]],
  ['concrete_20builder_20subclasses_20for_20nested_20types_17',['Concrete builder subclasses for nested types',['../group__nested-builders.html',1,'']]],
  ['concrete_20builder_20subclasses_20for_20numeric_20types_18',['Concrete builder subclasses for numeric types',['../group__numeric-builders.html',1,'']]],
  ['concrete_20builder_20subclasses_20for_20run_20end_20encoded_19',['Concrete builder subclasses for run-end encoded',['../group__run-end-encoded-builders.html',1,'']]],
  ['concrete_20builder_20subclasses_20for_20temporal_20types_20',['Concrete builder subclasses for temporal types',['../group__temporal-builders.html',1,'']]],
  ['concrete_20classes_20for_20binary_20string_20arrays_21',['Concrete classes for binary/string arrays',['../group__binary-arrays.html',1,'']]],
  ['concrete_20classes_20for_20nested_20arrays_22',['Concrete classes for nested arrays',['../group__nested-arrays.html',1,'']]],
  ['concrete_20classes_20for_20numeric_20arrays_23',['Concrete classes for numeric arrays',['../group__numeric-arrays.html',1,'']]],
  ['concrete_20classes_20for_20run_20end_20encoded_20arrays_24',['Concrete classes for run-end encoded arrays',['../group__run-end-encoded-arrays.html',1,'']]],
  ['concrete_20implementations_25',['Concrete implementations',['../group__dataset-implementations.html',1,'']]],
  ['concrete_20option_20classes_20for_20compute_20functions_26',['Concrete option classes for compute functions',['../group__compute-concrete-options.html',1,'']]],
  ['concrete_20scalar_20subclasses_27',['Concrete Scalar subclasses',['../group__concrete-scalar-classes.html',1,'']]],
  ['convenient_20expression_20creation_28',['Helpers for convenient expression creation',['../group__expression-convenience.html',1,'']]],
  ['convert_20a_20parquet_29',['Functions to convert a Parquet',['../group__parquet-to-arrow-schema-conversion.html',1,'']]],
  ['convert_20an_20arrow_30',['Functions to convert an Arrow',['../group__arrow-to-parquet-schema-conversion.html',1,'']]],
  ['correspond_31',['properties which correspond',['../group__parquet-file-format-arrow-reader-properties.html',1,'']]],
  ['creating_20an_20incremental_20csv_20writer_32',['Functions for creating an incremental CSV writer',['../group__csv-writer-factories.html',1,'']]],
  ['creating_20and_20executing_20execution_20plans_33',['Utilities for creating and executing execution plans',['../group__acero-api.html',1,'']]],
  ['creating_20data_20types_34',['Factory functions for creating data types',['../group__type-factories.html',1,'']]],
  ['creating_20filesystem_20instances_35',['Functions for creating FileSystem instances',['../group__filesystem-factories.html',1,'']]],
  ['creating_20recordbatchwriter_36',['Functions for creating RecordBatchWriter',['../group__record-batch-writer-factories.html',1,'']]],
  ['creation_37',['Helpers for convenient expression creation',['../group__expression-convenience.html',1,'']]],
  ['csv_20files_38',['High-level functions for writing CSV files',['../group__csv-write-functions.html',1,'']]],
  ['csv_20writer_39',['Functions for creating an incremental CSV writer',['../group__csv-writer-factories.html',1,'']]]
];
